### ISSUE TITLE
Utils::copyProperties

### ISSUE THREAD

**Issue by vinipaschoal** [EsfingeFramework/liveprog#1]
O **Utils::copyProperties** copia as propriedades de mesmo nome de um objeto para outro.

Se na  mudança da classe mudarmos o nome ou o tipo da variável esse método não resolve bem. 
Acho que um saveState funcionaria melhor. 
Por exemplo, numa mudança de tipo de String para um tipo numérico eu posso fazer um cast no construtor. Na copia dos parâmetros ele só não copia.

**Comment by vinipaschoal** [comment]
Na minha opinião, acho que quanto menos "obrigações" colocarmos no framework mais fácil fica para utilizá-lo, deixando-o menos invasivo na aplicação cliente. 

Neste caso da cópia das propriedades do objeto da versão antiga para o da nova versão, poderíamos adotar o princípio da "Convenção sobre Configuração" _**(CoC)**_, onde assumimos por padrão que os campos e seus tipos são iguais entre as versões, e podemos criar uma anotação que permita marcar as propriedades que não se encaixem nesse caso, permitindo talvez até especificar um conversor do valor antigo para o tipo da nova versão da classe. 

Dessa maneira, ficaria meio parecido como o que acontece com o JPA, por exemplo.

O que acham?

**Comment by guerraem** [comment]
Dá para ser uma mistura das duas abordagens...

Usa a cópia automática por reflexão como abordagem default. Caso mude alguma coisa, a classe pode implementar um método para fazer isso manualmente.

**Comment by vinipaschoal** [comment]
Criada a interface **IStateLoader**.
Se a nova versão da classe implementar essa interface, é criado um mapa com as propriedades e valores do objeto sendo substituído e enviado para a nova classe para ela carregar os valores como achar necessário.
Caso contrário, é utilizado reflexão através dos campos da nova classe.

**Comment by vinipaschoal** [comment]
Já implementado.
