### ISSUE TITLE
Utilizar classe ClassInstrumentation como interface de acesso ao bytecode

### ISSUE THREAD

**Issue by janosimas** [EsfingeFramework/liveprog#19]
Atualmente o acesso ao bytecode das classes é feito pela leitura dos arquivos .class ,
podemos utilizar a classe ClassInstrumentation como uma interface de acesso agnóstica.
Isso poermitiria que armazenassemos o bytecode num banco de dados ou até transmitido pela rede sem afetar o resto do programa.

**Comment by vinipaschoal** [comment]
Na versão atualizada do meu fork a classe nova que cumpre essas funções é a ClassInfo.

**Comment by vinipaschoal** [comment]
A ClassInfo é quem faz esse papel agora.
