### ISSUE TITLE
Perfil de teste

### ISSUE THREAD

**Issue by vinipaschoal** [EsfingeFramework/liveprog#3]
Na questão do perfil de teste, a sugestão de utilizar uma pilha no LiveClassFactory para armazenar as versões das classes também funciona. 
Quem estiver usando o perfil de teste pega a classe do topo da pilha. Quem estiver com o perfil normal pega a classe da base.

**Comment by janosimas** [comment]
@guerraem Estamos discutindo como vai ser o perfil de teste.
Estamos com duas possibilidades:

- O sistema funciona em de teste, o usuário faz as mudancas em runtime mas elas não entram na pilha. Quando terminar as mudanças ele commita e a mudanca é versionada e entra na pilha.

- O sistema tem um modo de teste que pode ser habilitado, quando ativado cada mudança é versionada e entra na pilha. Fora do modo de teste, o usuário só tem acesso a versão original.

**Comment by guerraem** [comment]
Teriam os seguintes estados:

ESTADO:PRODUÇÃO: Estado em que existe a pilha de versões e não existe versão candidata.
Ações:
->  ENVIAR NOVA VERSÃO: A versão candidata é guardada fora da pilha e passa ao estado CANDIDATA.
->  COMMIT: Erro.
-> CANCELAR CANDIDATA: Erro
-> ROLLBACK: Troca a versão atual pela anterior, elimina a versão atual da pilha e continua no estado PRODUCÃO.

ESTADO:CANDIDATA: Estado em que existe a pilha de versões e existe uma versão candidata.
Ações:
->  ENVIAR NOVA VERSÃO: A versão candidata atual é descartada, e nova versão candidata é guardada fora da pilha e continua no estado CANDIDATA.
->  COMMIT: A versão candidata é colocada no topo da pilha e passa a ser usada pelo sistema. O sistema fica sem versão candidata e vai para PRODUÇÃO.
-> CANCELAR CANDIDATA: A versão candidata atual é descartada e vai para PRODUÇÃO.
-> ROLLBACK: Elimina candidata, troca a versão atual pela anterior e vai para o estado PRODUCAO.

--------------------
Ao rodar o sistema no modo TESTE, o sistema irá verificar se existe uma versão candidata e usará ela no lugar da última versão da pilha.

**Comment by vinipaschoal** [comment]
Na nova versão do meu fork esse comportamento está implementado na classe **LiveClassFactory**, que pode ser iniciado em modo de teste ou produção (default).

**Comment by vinipaschoal** [comment]
Guerra, se na hora em que uma classe dinâmica for ser criada no Factory for informado se ela deve ser criada baseada na versão da classe de produção ou na de testes, isso atende ao seu requisito do perfil de testes?

Seria algo assim, por exemplo:

```
// classe dinâmica em perfil de testes
ClasseA classeA_tst = factory.createLiveClass(ClasseA.class, true);

// classe dinâmica em perfil de produção
ClasseA classeA_prd = factory.createLiveClass(ClasseA.class, false);
```

Daí quando uma nova versão da ClasseA subisse em modo teste, somente o primeiro objeto seria atualizado, e quando houvesse o commit da ClasseA, o segundo objeto seria atualizado.

Isso seria válido?

**Comment by vinipaschoal** [comment]
O framework possibilita trabalhar de 2 formas: 
- criar a **fábrica** de objetos dinâmicos em **modo normal**, e na criação dos objetos pode-se escolher entre criá-lo em modo produção ou modo teste
- criar a **fábrica** de objetos dinâmicos em **modo teste**; dessa maneira, qualquer que seja a forma dos objetos serem criados eles estarão em modo teste.
