### ISSUE TITLE
Substituição dinâmica de atributos do mesmo tipo da classe dinâmica

### ISSUE THREAD

**Issue by vinipaschoal** [EsfingeFramework/liveprog#5]
Casos a serem estudados/verificados:

- quando a classe dinâmica possui um atributo do mesmo tipo da classe;

- quando a classe dinâmica possui classes internas;

- quando a classe dinâmica possui anotações que fazem referência à própria classe ou à uma classe interna da classe dinâmica.

Verificar se o ASM consegue encontrar todos esses casos.
Verificar se o ASM consegue resolver esses casos, substituindo o nome da classe antiga pela nova versão da classe.

```
@LiveClass
public class ClasseD
{
	private ClasseD classeD;

	@Property(converter=FloatConverter.class)
	private Float idade;
	
	public class FloatConverter implements IPropertyConverter
	{
		public Object convert(Object obj)
		{
			if ( obj instanceof Integer )
				return ((Integer) obj).floatValue();
			
			return obj;
		}
	}
}
```

**Comment by guerraem** [comment]
Acho válido que em um primeiro momento crie-se algumas limitações nas classes que poderão ser substituídas. No caso, "não possuir classes internas" poderia ser uma dessas limitações.

**Comment by vinipaschoal** [comment]
A nova versão do meu fork está estruturada para checar se uma classe cumpre os requisitos para poder ser uma classe dinâmica.

A classe **InstrumentationService** tem um método com as regras que são verificadas na classe candidata a ser classe dinâmica.

A classe **LiveClassUpdateManager** tem um método que checa se a nova versão de uma classe dinâmica mantém a interface pública da classe original.

**Comment by vinipaschoal** [comment]
As verificações estão sendo feitas em **InstrumentationService.checkValidLiveClass**.

Numa futura versão, as regras dessa verificação podem ser transformadas em um HotSpot para que possam ser adicionadas/modificadas pelo usuário.
