### ISSUE TITLE
Exemplo de uso para testes

### ISSUE THREAD

**Issue by janosimas** [EsfingeFramework/liveprog#7]
Criar um pequeno programa que sirva como exemplo de uso e teste

**Comment by vinipaschoal** [comment]
Criado exemplo em Java Swing.

**Comment by vinipaschoal** [comment]
Vou criar o caso de demonstração baseado no programa exemplo Java Swing.

**Comment by vinipaschoal** [comment]
Já criei o jar do programa de demonstração, além de ter criado a apresentação em anexo para guiar a demonstração.
[Demonstracao LiveProg.pptx](https://github.com/EsfingeFramework/liveprog/files/2333787/Demonstracao.LiveProg.pptx)
